# Market Profile
MARKET_PROFILE = "NQ"


# NQ Settings
NQ_DELTA_SPIKE_THRESHOLD = 20
NQ_SWEEP_PRICE_MOVE = 0.5
NQ_SWEEP_VOLUME_THRESHOLD = 30
NQ_MIN_SCORE_FOR_TRADE = 0.75
NQ_PRICE_TOLERANCE = 0.25
# GC Settings
GC_DELTA_SPIKE_THRESHOLD = 12
GC_SWEEP_PRICE_MOVE = 0.3
GC_SWEEP_VOLUME_THRESHOLD = 20
GC_MIN_SCORE_FOR_TRADE = 0.75
GC_PRICE_TOLERANCE = 0.10

# Active Settings
if MARKET_PROFILE == "NQ":
    DELTA_SPIKE_THRESHOLD = NQ_DELTA_SPIKE_THRESHOLD
    SWEEP_PRICE_MOVE = NQ_SWEEP_PRICE_MOVE
    SWEEP_VOLUME_THRESHOLD = NQ_SWEEP_VOLUME_THRESHOLD
    MIN_SCORE_FOR_TRADE = NQ_MIN_SCORE_FOR_TRADE
    PRICE_TOLERANCE = NQ_PRICE_TOLERANCE

elif MARKET_PROFILE == "GC":
    DELTA_SPIKE_THRESHOLD = GC_DELTA_SPIKE_THRESHOLD
    SWEEP_PRICE_MOVE = GC_SWEEP_PRICE_MOVE
    SWEEP_VOLUME_THRESHOLD = GC_SWEEP_VOLUME_THRESHOLD
    MIN_SCORE_FOR_TRADE = GC_MIN_SCORE_FOR_TRADE
    PRICE_TOLERANCE = GC_PRICE_TOLERANCE